export const fakeAds = [
    {
      id: 1,
      name: "Xurupa",
      timePlaying: 4,
      daysOfWeek: [1, 3, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 2,
      name: "Loyde",
      timePlaying: 43,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: false,
    },
    {
      id: 3,
      name: "Nick",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 4,
      name: "King",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 5,
      name: "Berne",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 6,
      name: "Raphox",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 7,
      name: "Fera",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 8,
      name: "Toddy",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 9,
      name: "Berne",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 10,
      name: "Berne",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1040,
      hourEnd: 1400,
      voiceCall: true,
    },
    {
      id: 11,
      name: "Berne",
      timePlaying: 4,
      daysOfWeek: [0, 4, 5],
      hourStart: 1180,
      hourEnd: 1400,
      voiceCall: true,
    },
  ];